language: node_js
node_js:
- '0.10'
- '0.12'
before_install:
- npm install -g gulp
script:
- gulp test
notifications:
  slack:
    secure: TsncCt1cAd6J3kv3+THWGs9qC0r5HP0PqB0PAZVFLfNJKorogSgvIFUWf3ZMsMlN9nfAbbliv0nRBLs9DdU7Pz5kB+klCJko6iUGA0InnLC4XwUtzCVQxe/GK/eCES3+BkowSeCGRdy6jkw4jCJc8KJP5QENq+5gaEI454oW8qY=
